version: '3.3'

services:
  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proyecto_ci
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_container:5432/proyecto_ci
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
